### ISSUE TITLE
Think about renaming repo? Keystore typically is a repo of security certs...?

### ISSUE THREAD

**Issue by jgeewax** [stephenplusplus/gcloud-kvstore#2]
When I think of a "keystore" I typically think of either the Java KeyStore or a similar tool that stores credentials of some sort.

This project is awesome, using Cloud Datastore as a simple Key-Value storage system -- I wonder if it's worth renaming it to "gcloud-kvstore" or "gcloud-kv" ?

Might be at least worth the discussion...

**Comment by stephenplusplus** [comment]
Renamed!
